<!DOCTYPE html>
<html lang="{{LINGUAGEM}}" class="no-js">
<!-- BEGIN HEAD -->
<head>
   <meta charset="{{CHARSET}}" />
   <title>{{TITULO}}</title>
   <meta content="{{DESCRICAO}}" name="description" />
   <meta content="{{AUTOR}}" name="author" />
   <!-- BEGIN STYLES -->          
   <link href="{{PLUGINS}}bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
   <link href="{{CSS}}style.css" rel="stylesheet" type="text/css"/>
   <link href="{{CSS}}plugins.css" rel="stylesheet" type="text/css"/>
   <link href="{{CSS}}default.css" rel="stylesheet" type="text/css" id="style_color"/>
   <link href="{{CSS}}pages/login.css" rel="stylesheet" type="text/css"/>
   <link href="{{CSS}}custom.css" rel="stylesheet" type="text/css"/>
   <!-- END STYLES -->
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="login">
   <!-- BEGIN LOGIN -->
   <div class="content">
      <!-- BEGIN LOGIN FORM -->
      <form id="formulario" name="formulario" class="login-form" action="" method="post">
         <h3 class="form-title" align="center">Login</h3>
         <div class="alert alert-error hide">
            <button class="close" data-dismiss="alert"></button>
            <span>Informe o usuário e a senha.</span>
         </div>
         <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">Usuário</label>
            <div class="input-icon">
               <i class="icon-user"></i>
               <input class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="Usuário" name="username" id="username"/>
            </div>
         </div>
         <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">Senha</label>
            <div class="input-icon">
               <i class="icon-lock"></i>
               <input class="form-control placeholder-no-fix" type="password" autocomplete="off" placeholder="Senha" name="password" id="password"/>
            </div>
         </div>
         <div class="form-actions">
            <button type="button" id="btnEnviar" class="btn btn-primary pull-right">
            	Acessar
            </button>           
         </div>
         <input type="hidden" name='imgAjaxLoader' id='imgAjaxLoader' value="{{IMG}}icons/ajax-loader.gif"/>
      </form>
      <!-- END LOGIN FORM -->        
   </div>
   <!-- END LOGIN -->
   <!-- BEGIN JAVASCRIPTS -->
   <script src="{{PLUGINS}}jquery.min.js" type="text/javascript"></script>
   <script src="{{PLUGINS}}bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
   <script src="{{PLUGINS}}jquery.blockui.min.js" type="text/javascript"></script>  
   <script src="{{PLUGINS}}jquery.md5.js" type="text/javascript"></script>
   <script src="{{SCRIPTS}}pages/login.js" type="text/javascript"></script>
   <script src="{{SCRIPTS}}custom.js" type="text/javascript"></script>
   <script src="{{SCRIPTS}}custom/ClassUsuario.js" type="text/javascript"></script>
   <script>
   	  $(document).ajaxStop($.unblockUI);
      jQuery(document).ready(function() {     
        Login.init();
      });
   </script>
   <!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>