    <!-- BEGIN PAGE CONTAINER -->  
    <div class="page-container">
  
        <!-- BEGIN BREADCRUMBS -->   
        <div class="row breadcrumbs">
            <div class="container">
                <div class="col-md-4 col-sm-4">
                    <h1>ERRO</h1>
                </div>
                <div class="col-md-8 col-sm-8">
                    <ul class="pull-right breadcrumb">
                        <li><a href="/admin">PÁGINA PRINCIPAL</a></li>
                        <li class="active">{{CODE}}</li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- END BREADCRUMBS -->

        <!-- BEGIN CONTAINER -->   
        <div class="container margin-bottom-40">
          <div class="row">
            <div class="col-md-12 page-500">
                <div class="number">
                    {{CODE}}
                </div>
                <div class="details">
                    <h3>Opa! Você está perdido?</h3>
                    <p>
                        {{MESSAGE}} <br>
                        Acesse a <a href="/admin">página principal</a> ou tente novamente com outra rota!<br><br>
                    </p>
                </div>
            </div>
          </div>
        </div>
        <!-- END CONTAINER -->
  </div>
    <!-- END PAGE CONTAINER -->