<!-- BEGIN STYLE -->
<link href="{{CSS}}pages/contact.css" rel="stylesheet" type="text/css"/>
<!-- END STYLE -->
<!-- BEGIN CONTAINER -->
<div class="row">
    	<div id="content">
			<fieldset id='fdsContact'>
				<legend>Contato</legend>
				<div id='contentFormContact'></div>
			</fieldset>
			
			<fieldset id='fdsTelefone'>
				<legend>Telefone</legend>
				<div id='contentFormTelephone'></div>
			</fieldset>
			
			<fieldset id='fdsEmail'>
				<legend>Email</legend>
				<div id='contentFormEmail'></div>
			</fieldset>
    	</div>
    	<div id='divBtnSave'></div>
    	<div id='divBtnClean'></div>
    </div>
</div>
<div class="clearfix"></div>
<!-- END CONTAINER -->
<!-- BEGIN JAVASCRIPTS -->
<script src="{{SCRIPTS}}pages/contact.js" type="text/javascript"></script>
<!-- END JAVASCRIPTS -->