<!DOCTYPE html>
<html lang="{{LINGUAGEM}}">
<head>
	<meta charset="{{CHARSET}}" />
	<meta content="{{DESCRICAO}}" name="description" />
	<meta content="{{AUTOR}}" name="author" />
	
	<link href="{{PLUGINS}}bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
	<link href="{{PLUGINS}}jquery-ui/jquery-ui.min.css" rel="stylesheet" type="text/css" />
	<link href="{{CSS}}style.css" rel="stylesheet" type="text/css" />
	<link href="{{CSS}}custom.css" rel="stylesheet" type="text/css" />
    <link href="{{CSS}}plugins.css" rel="stylesheet" type="text/css"/>
</head>

<body>
	<!-- BEGIN PAGE CONTAINER -->
	<div class="page-container">
		{{CONTENT}}	
	</div>
	<input type="hidden" name='imgAjaxLoader' id='imgAjaxLoader' value="{{IMG}}icons/ajax-loader.gif"/>
	<!-- END PAGE CONTAINER -->
	
	<!-- BEGIN JAVASCRIPTS -->
	<script src="{{PLUGINS}}jquery.min.js" type="text/javascript"></script>
	<script src="{{PLUGINS}}jquery.mask.min.js" type="text/javascript"></script>
	<script src="{{PLUGINS}}bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="{{PLUGINS}}jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
	<script src="{{PLUGINS}}jquery.blockui.min.js" type="text/javascript"></script>
	<script src="{{SCRIPTS}}app.js" type="text/javascript"></script>
	<script src="{{SCRIPTS}}custom.js" type="text/javascript"></script>
	<script src="{{SCRIPTS}}modal.js" type="text/javascript"></script>
					
	<script type="text/javascript">
	$(document).ajaxStop($.unblockUI);
	
	jQuery(document).ready(function() {
		App.init();
		Contact.init();
	});
	</script>
	<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>