<!DOCTYPE html>
<html lang="{{LINGUAGEM}}">
    <head>
    	<meta charset="{{CHARSET}}" />
    	<meta content="{{DESCRICAO}}" name="description" />
    	<meta content="{{AUTOR}}" name="author" />
    	
    	<link href="{{PLUGINS}}bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    	<link href="{{CSS}}style.css" rel="stylesheet" type="text/css" />
    	<link href="{{CSS}}custom.css" rel="stylesheet" type="text/css" />
    	<link href="{{CSS}}pages/index.css" rel="stylesheet" type="text/css" />
        <link href="{{CSS}}plugins.css" rel="stylesheet" type="text/css"/>
    </head>
    
    <body>
        <!-- Trigger the modal with a button -->
        <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button>
        
        <!-- Modal -->
        <div id="myModal" class="modal fade" role="dialog">
          <div class="modal-dialog">
        
            <!-- Modal content-->
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">{{MODAL_HEADER}}</h4>
              </div>
              <div class="modal-body">
                {{CONTENT}}
              </div>
              <input type="hidden" name='imgAjaxLoader' id='imgAjaxLoader' value="{{IMG}}icons/ajax-loader.gif"/>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
              </div>
            </div>
        
          </div>
        </div>
        <!-- BEGIN JAVASCRIPTS -->
        <script src="{{PLUGINS}}jquery.min.js" type="text/javascript"></script>
        <script src="{{PLUGINS}}jquery.mask.min.js" type="text/javascript"></script>
        <script src="{{PLUGINS}}bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="{{PLUGINS}}jquery.blockui.min.js" type="text/javascript"></script>
        <script src="{{SCRIPTS}}app.js" type="text/javascript"></script>
        <script src="{{SCRIPTS}}custom.js" type="text/javascript"></script>
        <script src="{{SCRIPTS}}index.js" type="text/javascript"></script>
        				
        <script type="text/javascript">
        $(document).ajaxStop($.unblockUI);
        
        jQuery(document).ready(function() {
        	ControleMenuAtivo('pagina_principal');
        	App.init();
        	Index.init();
        });
        </script>
    <!-- END JAVASCRIPTS -->
    </body>
    <!-- END BODY -->
</html>