<!DOCTYPE html>
<html lang="{{LINGUAGEM}}">
<head>
	<meta charset="{{CHARSET}}" />
	<title>{{TITULO}}</title>
	
	<meta content="{{DESCRICAO}}" name="description" />
	<meta content="{{AUTOR}}" name="author" />
	
	<link href="{{PLUGINS}}bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
	<link href="{{CSS}}style.css" rel="stylesheet" type="text/css" />
	<link href="{{CSS}}custom.css" rel="stylesheet" type="text/css" />
	<link href="{{CSS}}pages/index.css" rel="stylesheet" type="text/css" />
</head>

<body>
<!-- BEGIN TOP BAR -->
<div class="front-topbar">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-sm-6"></div>
                    <div class="col-md-6 col-sm-6">
                        <ul class="list-unstyled inline" style="margin-left: 512px;">
                        	<li><a href="/logout">Logout</a></li>
                        </ul>
                    </div>
                </div>
            </div>        
        </div>
<!-- END TOP BAR -->
<!-- BEGIN HEADER -->
	<div class="header navbar navbar-default navbar-static-top">
		<div class="container">
			<!-- BEGIN TOP NAVIGATION MENU -->
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li class="dropdown pagina_principal">
						<a class="dropdown-toggle" data-hover="dropdown" data-delay="0"
						data-close-others="false" href="/admin">PÁGINA PRINCIPAL</a>
					</li>
				</ul>
			</div>
			<!-- BEGIN TOP NAVIGATION MENU -->
		</div>
	</div>
	<!-- END HEADER -->
	
	<!-- BEGIN PAGE CONTAINER -->
	<div class="page-container">
		{{CONTENT}}	
	</div>
	<input type="hidden" name='imgAjaxLoader' id='imgAjaxLoader' value="{{IMG}}icons/ajax-loader.gif"/>
	<!-- END PAGE CONTAINER -->

	<!-- BEGIN FOOTER -->
	<div class="copyright position">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-sm-8">
					<p>
						<span class="margin-right-10">
							{{ANO_ATUAL}} &copy; {{TITULO}}
						</span> 
					</p>
				</div>
			</div>
		</div>
	</div>
	<!-- END FOOTER -->

	<!-- BEGIN JAVASCRIPTS -->
	<script src="{{PLUGINS}}jquery.min.js" type="text/javascript"></script>
	<script src="{{PLUGINS}}bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="{{PLUGINS}}blockUI/jquery.blockUI.js" type="text/javascript"></script>
	<script src="{{SCRIPTS}}app.js" type="text/javascript"></script>
	<script src="{{SCRIPTS}}index.js" type="text/javascript"></script>
	<script src="{{SCRIPTS}}custom.js" type="text/javascript"></script>
	<script src="{{SCRIPTS}}tabs.js" type="text/javascript"></script>
					
	<script type="text/javascript">
	$(document).ajaxStop($.unblockUI);
	
	jQuery(document).ready(function() {
		ControleMenuAtivo('pagina_principal');
		App.init();
	});
	</script>
	<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>