<!-- BEGIN SAMPLE TABLE PORTLET-->
<div class="grid container portlet">
  <div class="portlet-title">
     <div class="caption"></i>{{TITLE}}</div>
  </div>
  <div class="portlet-body">
     <div class="table-responsive">
     	<!-- BEGIN TABLE -->
        <table class="table table-striped table-bordered table-advance table-hover" style="width:{{WIDTH}};">
           <thead>
              {{HEADER}}
           </thead>
           <tbody class='rowsClass' style="height:{{HEIGHT}};">
              {{ROWS}}
           </tbody>
        </table>
        <!-- END TABLE -->
     </div>
  </div>
</div>
<!-- END SAMPLE TABLE PORTLET-->
<!-- BEGIN PAGINATION -->
<div id='pagination' name='pagination'>
	<nav aria-label="Page navigation">
        <ul class="pagination">
            <li class="page-item">
                <a class="page-link" href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Anterior</span>
                </a>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">4</a></li>
            <li class="page-item"><a class="page-link" href="#">5</a></li>
            <li class="page-item">
                <a class="page-link" href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Próximo</span>
                </a>
            </li>
        </ul>
    </nav>
</div>
<!-- END PAGINATION -->
