<!-- BEGIN CONTAINER -->
<div class="container">
	<!-- BEGIN TITLE -->   
    <div class="row">
        <h2>GERENCIAR CONTATO</h2>
    </div>
    <!-- END TITLE -->
    
	<!-- BEGIN TABS -->
	<div class="row service-box">
        	<div id="content">
    			<fieldset id='fdsBtnRegister'>
    				<legend>Cadastrar contato</legend>
    				<div id='contentFormBtn'></div>
    			</fieldset>
    			
    			<fieldset id='fdsFormPesquisa'>
    				<legend>Pesquisa</legend>
    				<div id='contentFormPesquisa'></div>
    			</fieldset>
    			
    			<fieldset id='fdsGridContato'>
    				<legend>Formulário</legend>
    				<div id='contentGridContato'></div>
    			</fieldset>
    			
    			<!-- <fieldset id='fdsTelefone'>
    				<legend>Telefone</legend>
    				<div id='contentFormTelephone'></div>
    			</fieldset>
    			
    			<fieldset id='fdsEmail'>
    				<legend>Email</legend>
    				<div id='contentFormEmail'></div>
    			</fieldset> -->
        	</div>
        </div>
	</div>
	<!-- END TABS -->
	<div class="clearfix"></div>
</div>
<!-- END CONTAINER -->