<!-- BEGIN STYLE -->
<link href="{{CSS}}tabs.css" rel="stylesheet" type="text/css" />
<!-- END STYLE -->

<!-- BEGIN CONTAINER -->
<div class="container">
	<!-- BEGIN TITLE -->   
    <div class="row">
        <h2>GERENCIAR CONTATO</h2>
    </div>
    <!-- END TITLE -->
    
	<!-- BEGIN TABS -->
	<div class="row service-box">
	
		<div class="TabControl">
        	<div id="header">
        		<ul class="abas">
        			<div class='divAba'>
        				<div class="aba">
        					<span>Cadastro</span>
        				</div>
        			</div>
        			<div class='divAba'>
        				<div class="aba">
        					<span>Pesquisa</span>
        				</div>
        			</div>
        		</ul>
        	</div>
        	<div id="content">
        		<div class="conteudo">
        			Conteúdo da aba 1
        		</div>
        		<div class="conteudo">
        			Conteúdo da aba 2
        		</div>
        	</div>
        </div>
	</div>
	<!-- END TABS -->

	<div class="clearfix"></div>
</div>
<!-- END CONTAINER -->