<!-- BEGIN CONTAINER -->
<div class="container">
	<!-- BEGIN TITLE -->   
    <div class="row">
        <h2>GERENCIAR CONTATO</h2>
    </div>
    <!-- END TITLE -->
    
	<div class="row service-box">
        	<div id="content">
    			<fieldset id='fdsBtnRegister'>
    				<legend>Cadastrar contato</legend>
    				<div id='contentFormBtn'></div>
    			</fieldset>
    			
    			<fieldset id='fdsFormPesquisa'>
    				<legend>Pesquisa</legend>
    				<div id='contentFormPesquisa'></div>
    			</fieldset>
    			
    			<fieldset id='fdsGridContato'>
    				<legend>Relatório</legend>
    				<div id='contentGridContato'></div>
    			</fieldset>
        	</div>
        </div>
	</div>
	<div class="clearfix"></div>
</div>
<!-- END CONTAINER -->